Make Stream as Duplex type in abortable-iterator
ChainSafe/libp2p-ts pull request #15
Opened 2020-07-23 08:54 UTC by tuyennhv

2020-07-23 08:57 UTC, mpetrunic requested changes

2020-07-23 08:57 UTC, mpetrunic commented on types/interface-connection/index.d.ts
>  declare interface Stream {
```suggestion
declare interface Stream<TSource = unknown, TReturn = unknown> {
```

and use thos on sink and source methods :slightly_smiling_face:

2020-07-23 10:12 UTC, mpetrunic approved these changes

2020-07-24 05:40 UTC, wemeetagain approved these changes

2020-07-24 05:40 UTC, merged